### ISSUE TITLE
Crash on pdb reading

### ISSUE THREAD

**Issue by mafaca** [smx-smx/PDBSharp#3]
Install https://download.unity3d.com/download_unity/c6fa43736cae/Windows64EditorInstaller/UnitySetup64-2017.4.30f1.exe
Try to process Editor/unity_x64.pdb => dumper crashes

**Comment by smx-smx** [comment]
Thanks for reporting @mafaca

Fixed in 1747089823acb635ccba8b24483f1a9b47a4dbb7
Crash was due to missing size guards in the TPI Hash reader
