### ISSUE TITLE
-print argument crashes program

### ISSUE THREAD

**Issue by mafaca** [smx-smx/PDBSharp#4]
wip branch
Running a dumper with -print argument causes the program to crash

**Comment by smx-smx** [comment]
I fixed the crash, now i have to look why the feature got broken.

**Comment by mafaca** [comment]
I don't think this commit fixes the issue, because it doesn't enumerate modules.
https://github.com/smx-smx/PDBSharp/blob/master/PDBSharp.Dumper/Program.cs#L145
maybe i don't understand something tho.
